"""
modules/exports.py
Reads Brazilian export data from data/exports_summary.csv (generated by GitHub Actions).
Source: USDA PSD (Production, Supply and Distribution) — fas.usda.gov
Units: 1000 Metric Tons
"""

import os
import json
import pandas as pd

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")

SUMMARY_FILE = os.path.join(DATA_DIR, "exports_summary.csv")
COUNTRY_FILE = os.path.join(DATA_DIR, "exports_by_country.csv")
META_FILE    = os.path.join(DATA_DIR, "exports_meta.json")


def _load_csv(path: str) -> pd.DataFrame:
    if not os.path.exists(path):
        print(f"[exports.py] File not found: {path}")
        return pd.DataFrame()
    try:
        return pd.read_csv(path)
    except Exception as e:
        print(f"[exports.py] Error reading {path}: {e}")
        return pd.DataFrame()


def get_last_updated() -> str:
    if not os.path.exists(META_FILE):
        return "unknown"
    try:
        with open(META_FILE) as f:
            return json.load(f).get("last_updated", "unknown")
    except Exception:
        return "unknown"


def get_exports_by_commodity(commodity: str, year: int) -> pd.DataFrame:
    """
    Returns export volume for a commodity/year from USDA PSD.
    Page 3 — Brazil Exports.
    Note: USDA PSD does not provide by-destination breakdown.
    Returns a single-row DataFrame with total volume.
    """
    df = _load_csv(SUMMARY_FILE)

    if df.empty:
        return pd.DataFrame(columns=["Commodity", "Year", "Exports (1000 MT)"])

    mask = (df["Commodity"] == commodity) & (df["year"] == year)
    df = df[mask].copy()

    if df.empty:
        return pd.DataFrame(columns=["Commodity", "Year", "Exports (1000 MT)"])

    rename = {"year": "Year", "Exports (1000MT)": "Exports (1000 MT)"}
    df = df.rename(columns=rename)

    keep = [c for c in ["Commodity", "Year", "Exports (1000 MT)"] if c in df.columns]
    return df[keep].reset_index(drop=True)


def get_annual_exports_summary(year: int = 2023) -> pd.DataFrame:
    """
    Returns total export volume per commodity for a given year.
    Page 1 — Overview bar chart.
    Columns: Commodity, Exports (USD)  [kept as-is for app.py compatibility]
    Note: unit is actually 1000 MT from USDA PSD, not USD.
    """
    df = _load_csv(SUMMARY_FILE)

    if df.empty:
        return pd.DataFrame(columns=["Commodity", "Exports (USD)"])

    df = df[df["year"] == year].copy()

    if df.empty:
        return pd.DataFrame(columns=["Commodity", "Exports (USD)"])

    # Rename to match app.py expectation (column name "Exports (USD)")
    df = df.rename(columns={"Exports (1000MT)": "Exports (USD)"})

    keep = [c for c in ["Commodity", "Exports (USD)"] if c in df.columns]
    df = df[keep]
    df = df[df["Exports (USD)"] > 0].reset_index(drop=True)

    return df
