"""
modules/exports.py
Brazilian export data — reads from data/exports_*.csv (generated by GitHub Actions).
Falls back to empty DataFrames with a clear warning if files are missing.
"""

import os
import json
import pandas as pd
from datetime import datetime

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")

COUNTRY_FILE  = os.path.join(DATA_DIR, "exports_by_country.csv")
SUMMARY_FILE  = os.path.join(DATA_DIR, "exports_summary.csv")
META_FILE     = os.path.join(DATA_DIR, "exports_meta.json")


def _load_csv(path: str) -> pd.DataFrame:
    """Load a CSV file, returning empty DataFrame on failure."""
    if not os.path.exists(path):
        print(f"[exports.py] File not found: {path}")
        return pd.DataFrame()
    try:
        return pd.read_csv(path)
    except Exception as e:
        print(f"[exports.py] Error reading {path}: {e}")
        return pd.DataFrame()


def get_last_updated() -> str:
    """Returns the ISO timestamp of the last data update, or 'unknown'."""
    if not os.path.exists(META_FILE):
        return "unknown"
    try:
        with open(META_FILE) as f:
            meta = json.load(f)
        return meta.get("last_updated", "unknown")
    except Exception:
        return "unknown"


def get_exports_by_commodity(commodity: str, year: int) -> pd.DataFrame:
    """
    Returns top export destinations for a given commodity and year.
    Used by app.py Page 3 (Brazil Exports).

    Returns DataFrame with columns: Country, Exports (USD), Weight (kg)
    """
    df = _load_csv(COUNTRY_FILE)

    if df.empty:
        return pd.DataFrame(columns=["Country", "Exports (USD)", "Weight (kg)"])

    # Filter by commodity and year
    mask = (df["commodity"] == commodity) & (df["year"] == year)
    df = df[mask].copy()

    if df.empty:
        return pd.DataFrame(columns=["Country", "Exports (USD)", "Weight (kg)"])

    # Rename API columns to display names
    rename = {}
    if "country" in df.columns:
        rename["country"] = "Country"
    if "metricFOB" in df.columns:
        rename["metricFOB"] = "Exports (USD)"
    if "metricKG" in df.columns:
        rename["metricKG"] = "Weight (kg)"

    df = df.rename(columns=rename)

    keep = [c for c in ["Country", "Exports (USD)", "Weight (kg)"] if c in df.columns]
    df = df[keep]

    if "Exports (USD)" in df.columns:
        df = df.sort_values("Exports (USD)", ascending=False).head(20)

    return df.reset_index(drop=True)


def get_annual_exports_summary(year: int = 2023) -> pd.DataFrame:
    """
    Returns total exports per commodity for a given year.
    Used by app.py Page 1 (Overview) bar chart.

    Returns DataFrame with columns: Commodity, Exports (USD)
    """
    df = _load_csv(SUMMARY_FILE)

    if df.empty:
        return pd.DataFrame(columns=["Commodity", "Exports (USD)"])

    df = df[df["year"] == year].copy()

    if df.empty:
        return pd.DataFrame(columns=["Commodity", "Exports (USD)"])

    keep = [c for c in ["Commodity", "Exports (USD)"] if c in df.columns]
    df = df[keep]

    df = df[df["Exports (USD)"] > 0].reset_index(drop=True)

    return df
